### ISSUE TITLE
Pricing Structure

### ISSUE THREAD

**Issue by scottwarren** [benmort/rciceberg#23]
Postage:

![image](https://cloud.githubusercontent.com/assets/2718494/7469511/cffd961a-f357-11e4-9119-89ba641dfa38.png)

Memberful:
  All: 9.9% + 30c transaction fee
Stripe:
  Domestic cards: 1.75% + 30c
  International + AmEx: 2.9% + 30c

Costs:
Tampons: ~$6
Chocolates: ~$5
Transaction Fees = (Price) 15.95 \* ((Memberful) 0.099 + (Stripe) 0.00175) + (Memberful) 30 + (Stripe)0.30 = ~$2.20
Price Point: $15.95

Price - Fees = 15.95 - 2.20 = 13.75
Tampons + Chocolates = 11
Profit: 13.75 - 11 = 2.75/user/month
# Todo
- [ ] Find lower transaction fee
- [ ] Find lower costing but still as high quality tampons
- [ ] Find good low cost premium chocolates
