### ISSUE TITLE
Responsive Menu is broken/missing on Mobile

### ISSUE THREAD

**Issue by scottwarren** [benmort/rciceberg#31]
# Todo
- [ ] Fix mobile responsive header
- [ ] Normal header works as expected
- [ ] Make sure elements throughout page (such as price table) work as expected
